from django import forms

class InputForm(forms.Form):
    Radius_mean = forms.DecimalField()
    Texture_mean = forms.DecimalField()
    Perimeter_mean = forms.DecimalField()
    Area_mean = forms.DecimalField()
    Smoothness_mean = forms.DecimalField()
    Compactness_mean = forms.DecimalField()
    Concavity_mean  = forms.DecimalField()
    Concavity_points_se  = forms.DecimalField()
    Concave_points_mean = forms.DecimalField()
    Symmetry_mean  = forms.DecimalField()
    Fractal_dimension_mean  = forms.DecimalField()
    Radius_se = forms.DecimalField()
    Texture_se = forms.DecimalField()
    Perimeter_se =  forms.DecimalField()
    Area_se = forms.DecimalField()
    Smoothness_se  = forms.DecimalField()
    Compactness_se = forms.DecimalField()
    Concavity_se = forms.DecimalField()
    Symmetry_se = forms.DecimalField()
    Fractal_dimension_se = forms.DecimalField()
    Radius_worst= forms.DecimalField()
    Texture_worst = forms.DecimalField()
    Perimeter_worst = forms.DecimalField()
    Area_worst = forms.DecimalField()
    Smoothness_worst  = forms.DecimalField()
    Compactness_worst  = forms.DecimalField()
    Concavity_worst = forms.DecimalField()
    Concave_points_worst = forms.DecimalField()
    Symmetry_worst = forms.DecimalField()
    Fractal_dimension_worst = forms.DecimalField()
    
    